### ISSUE TITLE
反映されていない

### ISSUE THREAD

**Issue by Pleurotus-eryngii** [Hayabusa58/FakeUrienMod#1]
こちらの開発環境にて、MOD自体は読み込まれているもののレシピもアイテムも追加されていないという現象が発生しております。恐らくCoreでの処理がうまくいっていないと思われ。
public static UrienModCore instanse;みたいな形式のやり方はよく知らないのですが、そちらではちゃんと動作してますか?

**Comment by haya58** [comment]
なるほど・・・ちょっと書きなおしてみます

**Comment by Pleurotus-eryngii** [comment]
もう修正はじめてくださってるところに悪いのですが、基本的に剣などのインスタンス生成はCore(＠MODがあるとこ）で行うみたいです。レシピの場合もたぶん同様(Wiki、れぎんさんのGithub参照)。
ただ今回の場合剣のソースが長いので例外的に分けたほうがいいのかもしれませんが。

**Comment by haya58** [comment]
ふむふむ・・・登録処理のみCoreクラスで行わせる形にしてみます．

**Comment by Pleurotus-eryngii** [comment]
はやぶささんのコードをもとに、れぎん氏のBowを参考にしつつ訂正した結果、現時点で求められる動きを確認しました。
