### ISSUE TITLE
Modのライセンスについて

### ISSUE THREAD

**Issue by haya58** [Hayabusa58/FakeUrienMod#6]
開発作業お疲れ様です．
念のため皆様の意見を伺いたいのですが，modに付与するライセンスはどうしましょうか？
個人的な考えでは[クリエイティブ・コモンズ 表示 4.0 国際](http://creativecommons.org/licenses/by/4.0/)を使用したいと考えているのですがどうでしょう．

**Comment by Pleurotus-eryngii** [comment]
英語適当に読みましたが、
･商業利用可
･変更など可能
･再配布可
･ライセンス記載必須
という感じでしょうか。この内容であっているとすると特に問題は無いかと思われます。
ただ、フォーラムにライセンスのリンクだけ貼っても読まない人はいそうなので、日本語での解説も必要かと

**Comment by haya58** [comment]
ありがとうございます。  
このライセンスにした場合はそのドキュメントには日本語版もあるのでそれを貼っておくのと多少かみ砕いた解説は載せる予定です。

**Comment by Pleurotus-eryngii** [comment]
公開したみたいなのでとりあえず閉めます
