### ISSUE TITLE
周囲のプレイヤーに対するウィザー効果付与について

### ISSUE THREAD

**Issue by haya58** [Hayabusa58/FakeUrienMod#7]
開発作業お疲れ様です．
当初の依頼では（任意で構わないとありましたが）周囲のプレイヤーにも一定時間ウィザー効果を付与することも入っていましたが，どうしましょうか？手間も増えますし，いったんリリースしてもいいかなとは思ったのですが・・・
簡単に実装できるようならもちろん書いていただいても結構です．

**Comment by Pleurotus-eryngii** [comment]
よく覚えて無いですが、現行のコードのPotionEffectのところの指定を何とかして、あとは鯖側の処理をどうにかするとたぶんできそうです。ですがまあ、一度リリースして依頼者の方に確認してもいいかと

**Comment by Pleurotus-eryngii** [comment]
でみさんが実装してくださったようなので閉じます
